name = "checkoutmaxx"
client_id = "0a60bbe935cef2f46838acec2b3918d8"
application_url = "https://checkoutmaxx-rt55.vercel.app"
embedded = true

[access_scopes]
scopes = "read_orders,read_checkouts,write_pixels,read_customer_events,read_analytics"

[auth]
redirect_urls = [
  "https://checkoutmaxx-rt55.vercel.app/api/auth/callback"
]

[webhooks]
api_version = "2025-04"

[webhooks.privacy_compliance]
customer_data_request_url = "https://checkoutmaxx-rt55.vercel.app/api/webhooks/customers/data-request"
customer_deletion_url = "https://checkoutmaxx-rt55.vercel.app/api/webhooks/customers/redact"
shop_deletion_url = "https://checkoutmaxx-rt55.vercel.app/api/webhooks/shop/redact"

[pos]
embedded = false

[[extensions]]
type = "web_pixel"
handle = "cart-monitor"