name = "couponmaxx"
client_id = "ef34a3eb07ec4333b42d63385823433b"
application_url = "https://couponmaxx.vercel.app"
embedded = true

[access_scopes]
scopes = "read_orders,read_checkouts,write_pixels,read_customer_events,read_analytics"

[auth]
redirect_urls = [
  "https://couponmaxx.vercel.app/api/auth/callback"
]

[webhooks]
api_version = "2025-04"

[webhooks.privacy_compliance]
customer_data_request_url = "https://couponmaxx.vercel.app/api/webhooks/customers/data-request"
customer_deletion_url = "https://couponmaxx.vercel.app/api/webhooks/customers/redact"
shop_deletion_url = "https://couponmaxx.vercel.app/api/webhooks/shop/redact"

[pos]
embedded = false

[[extensions]]
type = "web_pixel"
handle = "cart-monitor"