api_version = "2025-07"

[[extensions]]
uid = "600deb5a-0084-db1f-cf54-0e2c2e15d1dcd25b12e0"
type = "ui_extension"
name = "CouponMaxx Checkout Recovery"
handle = "checkout-recovery"
network_access = true

[[extensions.targeting]]
module = "./src/Checkout.tsx"
target = "purchase.checkout.reductions.render-after"

[[extensions.capabilities]]
name = "network_access"
allowed_domains = ["couponmaxx.vercel.app"]
